{% set name = "iopath" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iopath-{{ version }}.tar.gz
  sha256: 3311c16a4d9137223e20f141655759933e1eda24f8bff166af834af3c645ef01

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<=36]

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - tqdm
    - typing_extensions
    - portalocker
    - dataclasses  # [py<37]

{% set deselect_tests = "" %}
# Expected None, but tests/test_s3.py::test_bucket_defined returned False, which will be an error in a future version of pytest.  Did you mean to use `assert` instead of `return`?
{% set deselect_tests = " --deselect=tests/async_torch_test.py::TestDriver::test" %}

test:
  source_files:
    - tests
  imports:
    - iopath
  commands:
    - pip check
    - pytest -v {{ deselect_tests }} tests
  requires:
    - pip
    - pytest
    # Needs for async_torch_test.py
    - pytorch

about:
  home: https://github.com/facebookresearch/iopath
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Lightweight I/O abstraction library
  description: A library for providing I/O abstraction.
  dev_url: https://github.com/facebookresearch/iopath
  doc_url: https://github.com/facebookresearch/iopath/blob/main/README.md

extra:
  recipe-maintainers:
    - thewchan
