{% set name = "iopath" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iopath-{{ version }}.tar.gz
  sha256: 3311c16a4d9137223e20f141655759933e1eda24f8bff166af834af3c645ef01

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - tqdm
    - typing_extensions
    - portalocker
    - dataclasses  # [py<37]

{% set ignore_tests = "" %}
# $PREFIX/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1 (_poll_jobs)
#{% set ignore_tests = " --ignore=tests/async_torch_test.py" %}
# Provides infinity tests execution (tests runs forever)
{% set ignore_tests = ignore_tests + " --ignore=tests/async_writes_test.py" %}

{% set deselect_tests = "" %}
# AssertionError: 'test\\a.txt' != 'test/a.txt'
{% set deselect_tests = " --deselect=tests/test_file_io.py::TestNativeIO::test_get_path_with_cwd" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_file_io.py::TestLazyPath::test_join" %}  # [win]
#AssertionError: '\\\\?\\C:\\cygwin64\\tmp\\tmp3abxq5np\\te[46 chars].txt' != 'C:\\cygwin64\\tmp\\tmp3abxq5np\\test_file[39 chars].txt'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_file_io.py::TestNativeIO::test_symlink" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - iopath
  commands:
    - pip check
    - pytest -vvv {{ ignore_tests }} {{ deselect_tests }} tests
  requires:
    - pip
    - pytest
    - pytorch

about:
  home: https://github.com/facebookresearch/iopath
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Lightweight I/O abstraction library.
  description: A library for providing I/O abstraction.
  doc_url: https://github.com/facebookresearch/iopath/blob/main/README.md
  dev_url: https://github.com/facebookresearch/iopath

extra:
  recipe-maintainers:
    - thewchan
