{% set name = "iopath" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3f17a6558fa62fdc2ab1ecdf7c106576167fb8bb19f1612289fd88467535ad7a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - dataclasses
    - portalocker
    - python >=3.6
    - tqdm

test:
  imports:
    - iopath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facebookresearch/iopath
  license: MIT
  license_file: LICENSE
  summary: Lightweight I/O abstraction library


extra:
  recipe-maintainers:
    - thewchan
